### ISSUE TITLE
Add Online Game Demo

### ISSUE THREAD

**Issue by panmona** [IronyOfRyan/reacttactoe#1]
Have you thought about making an online version of the game available? (For example with a deploy to Github Pages / Surge.sh / Netlify / Now.sh /... -> these are all services that offer free hosting of your frontend project)

**Comment by UniversallyRy** [comment]
Thanks for the tip! I'll definitely try to get that up and running in the near future.

**Comment by panmona** [comment]
Wouldn't recommend Heroku for a frontend project but it works, cool!
